config/routes.rb
Foodbank:: Application.routes.draw do 
    root 'sessions#new'
    #resources :forms, :fb_agencies, :validate_step_fb_agencies, :meal_programs, :grocery_plans, :food_safeties, :direct_connect_programs,
    #:ef_programs, :program_procedures, :signature_documents, :proxy_forms, :part_six_forms, :part_seven_eight_forms,
    resources :fb_agencies, :grocery_plans, :food_safeties, :meal_programs, :ef_programs, :direct_connect_programs, :part_six_forms, :part_seven_eight_forms, :forms

 

=begin
    resource :wizard do
        get :step1
        get :step2
        get :step3
    
        post :validate_step
    end
=end

   # get '/forms/step2'
   # get '/forms/step3'
    #get '/forms/fb_agencies/index'
    #get '/forms/foodsafety' 
    #get '/forms/mealplan'
    #get '/forms/groceryplan'
    #get '/forms/directconnect'
    #get '/forms/emergencyfood'
    #get '/forms/part6'
    #get '/forms/part7_8'
   # get '/forms.css'

   

    get '/forms/foodsafety'
    get '/forms/mealplan'
    get '/forms/groceryplan'
    get '/forms/directconnect'
    #get '/forms/emergencyfood'
    get '/forms/part6'
    get '/forms/part7_8'
    get "howto/:howto"=>"howto#show"
    
   get 'signup'  => 'users#new'
   resources :users
  
   get '/login' => 'sessions#new'
  
   post 'login' => 'sessions#create'
  
   delete 'logout' => 'sessions#destroy'

 
end

app/models/fb_agency.rb
class FbAgency < ActiveRecord::Base
 #belongs_to :fb_agencies
    
    include MultiStepModel
    def self.total_steps
        3
    end
    validates :AgencyName, presence: true, if: :step1?
    validates :DateOfVerification, presence: true, if: :step2?
    validates :AgencyCounty, presence: true, if: :step1?
    validates :AgencyNumber, numericality: true, if: :step1?
    validates :TodaysDate, presence: true, if: :step1?
    validates :DofLastMonitor, presence: true, if: :step1?
    validates :ParentAgency, presence: true, if: :step1?
    validates :PAgencyNum, numericality: true,if: :step1?
    validates :SiteAddress, presence: true, if: :step1?
    validates :SiteNumber, numericality: true, if: :step1?
    validates :ContactName, presence: true, if: :step1?
    validates :ContactNum, numericality: true, if: :step1?
    validates :Director, presence: true, if: :step1?
    validates :DirectorNum, numericality: true, if: :step1?
    validates :AdditionalContact, presence: true, if: :step1?
    validates :AdditionalNum, numericality: true, if: :step1?
    validates :PrimaryEmail, presence: true, format: { with: /@/ }, if: :step2?
    validates :DateMostRecentTraining, presence: true, if: :step2?
    validates :TaxExemptOnFile, :presence => true, :inclusion => { :in => %w(Yes No), :allow_blank => false }, if: :step2?
    validates :IRSVerification, :presence => true, :inclusion => { :in => %w(Yes No), :allow_blank => false }, if: :step2?
    validates :EEP, :presence => true, if: :step2?
    validates :DateOfContract, presence: true, if: :step3?
    validates :SoupKitchen, presence: true, :allow_blank => true, if: :step3?
    validates :GroupHome, presence: true, :allow_blank => true, if: :step3?
    validates :Shelter, presence: true, :allow_blank => true, if: :step3?
    validates :Daycare, presence: true, :allow_blank => true, if: :step3?
    validates :YouthProgram, presence: true, :allow_blank => true, if: :step3?
    validates :FoodPantry, presence: true, :allow_blank => true, if: :step3?
    validates :Seasonal, presence: true, :allow_blank => true, if: :step3?
    validates :MobilePantry, presence: true, :allow_blank => true, if: :step3?
    validates :Backpack, presence: true, :allow_blank => true, if: :step3?
    validates :PersonInterviewed, presence: true, if: :step3?
    validates :DaysOfOperation, presence: true, if: :step3?
    validates :SingleAudit, presence: true, if: :step3?
    validates :HandicapAccessible, :presence => true, :allow_blank => true, if: :step3?
   
end

app/controllers/fb_agencies_controller.rb
class FbAgenciesController < ApplicationController
#before_action :load_fbagency


  def index
    @fb_agencies = FbAgency.all
    respond_to do |format|
        format.html
        format.csv {render text: @agencies.to_csv, nil:ignore}
        format.xls { send_data @agencies.to_csv(col_sep: "\t") }
    end
  end
  
  def import
        if params[:file].nil?
            flash[:warning] = "Please Select a File"
                     -# fb_agencies_path may need to be replaced with proper path
            redirect_to fb_agencies_path notice: "Not Imported."
        else
            Agency.import(params[:file])
            flash[:notice] = "Data imported"
                     -# fb_agencies_path may need to be replaced with proper path
            redirect_to fb_agencies_path notice: "Data Imported."
        end
  end

  def show
  end
  
  def new
    @wizard = ModelWizard.new(FbAgency, session, params).start
    @fb_agency = @wizard.object
    logger.debug "New agency: #{@fb_agency.attributes.inspect}"
  end

  def create
    @wizard = ModelWizard.new(FbAgency, session, params, agencies_params).continue
    @fb_agency = @wizard.object
    if @wizard.save
      @fb_agency = FbAgency.create!(agencies_params)
        session[:fbagency_attributes] = nil
        render '/forms/groceryplan'
    else
      render :new
    end
  end 
    def edit
      #@wizard = ModelWizard.new(@fb_agencies, session, params).start
      @fb_agency = FbAgency.find(params[:id])
    end
    def update
      #@wizard = ModelWizard.new(@fb_agencies, session, params, agencies_params).continue
      @fb_agency = FbAgency.find params[:id]
      @fb_agency.update_attributes!(agencies_params)
      flash[:notice] = "#{@fb_agency.AgencyName} was successfully updated."
      redirect_to fb_agencies_path
    end
    def destroy
        @fb_agency = FbAgency.find(params[:id])
        @fb_agency.destroy
        flash[:notice] = "Agency '#{@fb_agency.AgencyName}' deleted."
        redirect_to fb_agencies_path
    end
    
    def agencies_params
        params.require(:fb_agency).permit(:current_step, :AgencyName, :AgencyCounty, :AgencyNumber, :TodaysDate, :DofLastMonitor, :ParentAgency,
        :PAgencyNum, :SiteAddress, :SiteNumber, :ContactName, :ContactNum, :Director, :DirectorNum, :AdditionalContact, :AdditionalNum, 
        :PrimaryEmail, :DateMostRecentTraining, :TaxExemptOnFile, :IRSVerification, :DateOfVerification, :EEP, :DateOfContract,
        :SoupKitchen, :GroupHome, :Shelter, :Daycare, :YouthProgram, :FoodPantry, :Seasonal, :MobilePantry, :Backpack, :PersonInterviewed, :DaysOfOperation, :SingleAudit, :HandicapAccessible)
    end
end

app/views/fb_agencies/_form.html.haml
- if @fb_agency.errors.any?
  #errors
    %ul
      - @fb_agency.errors.full_messages.each do |msg|
        %li= msg
= form_for @fb_agency do |f|
  - if params[:all].nil?
    = render 'fb_agencies/steps/current_step', f: f
  - else
    = render 'fb_agencies/steps/all_steps', f

app/views/fb_agencies/edit.html.haml
%h1 Edit Agency

= render 'form' 
= link_to 'Show', @fb_agency

= link_to 'Back To All FB Agencies', fb_agencies_path

app/views/fb_agencies/index.html.haml
%h1 Agencies

%table#forms
    %thead 
    %tr
        %th Agency Name
        %th Completion Date
        = link_to "How-To", "howto/howto"
        %br
        = link_to 'Add New Agency (with steps)', new_fb_agency_path 
        %th Edit Agency
        %th Delete Agency

    %tbody
    - @fb_agencies.each do |agency|
        %tr
            %td= agency.AgencyName
            %td= agency.DateOfVerification
            %td= link_to "Edit", edit_fb_agency_path(agency)
            %td= link_to 'Delete', fb_agency_path(agency), :method => :delete
            
%h1 Import:
                   -# fb_agencies_path may need to be replaced with proper path
    = form_tag import fb_agencies_path, multipart: true do
    = submit_tag 'Import'
    = file_field_tag :file

            
        

app/views/fb_agencies/new.html.haml
%h1 New Agency (step: #{@fb_agency.current_step + 1}  )
= render 'form'

|
= link_to 'Back', fb_agencies_path

app/views/fb_agencies/old_new.html.haml
%body
  !!! XML
  #wrapper
 
    = form_tag  fb_agencies_url :method => :post do
      = hidden_field_tag "current_step", "index"
      .form-group
        .row
          .col-xs-2.pull-right.col-sm-3.rm
            = label :fb_agency, :AgencyCounty, 'Agency County'
            = text_field :fb_agency, :AgencyCounty
            
        .row
          .col-xs-2.pull-right.col-sm-3.rm
            = label :fb_agency, :AgencyNumber, 'Agency #'
            = text_field :fb_agency, :AgencyNumber
            
        .row
          .text-center
            %h2 Network Partner Monitoring Form
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :TodaysDate, "Today's Date"
            = text_field :fb_agency, :TodaysDate
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :DofLastMonitor,  'Date of Last Monitor'
            = text_field :fb_agency, :DofLastMonitor
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :AgencyName, 'Agency Name'
            = text_field :fb_agency, :AgencyName
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :AgencyNumber, 'Agency #'
            = text_field :fb_agency, :AgencyNumber
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :ParentAgency, 'Parent Agency'
            = text_field :fb_agency, :ParentAgency
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :PAgencyNum, 'Agency #'
            = text_field :fb_agency, :PAgencyNum
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :SiteAddress, 'Site Address'
            = text_field :fb_agency, :SiteAddress
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :SiteNumber, 'Phone #'
            = text_field :fb_agency, :SiteNumber 
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :ContactName, 'Contact Name'
            = text_field :fb_agency, :ContactName
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :ContactNum,  'Phone #'
            = text_field :fb_agency, :ContactNum
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :Director, "Director's Name"
            = text_field :fb_agency, :Director
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :DirectorNum, 'Phone #'
            = text_field :fb_agency, :DirectorNum
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :AdditionalContact, 'Additional Contact Name'
            = text_field :fb_agency, :AdditionalContact
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :AdditionalNum,'Phone #'
            = text_field :fb_agency, :AdditionalNum
        .row.pull-right.rm
          = submit_tag 'Next'

app/views/fb_agencies/page2.html.haml
%body
  !!! XML
  #wrapper
    = form_tag fb_agencies_url :method => :post do
      .form-group
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :PrimaryEmail, 'Primary Email'
            = text_field :fb_agency, :PrimaryEmail
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :DateMostRecentTraining, 'Date of Most Recent Food Safety Training (YYYY-MM-DD)'
            = text_field :fb_agency, :DateMostRecentTraining
        .row.yes-no-quest
          %p.pull-left.col-sm-6
            = label :fb_agency, :TaxExemptOnFile, 'Does Northern Illinois Food Bank have current verification of tax exempt status on file?'
          .pull-right.col-sm-12
            %label.radio-inline Yes
            = text_field :fb_agency, :TaxExemptOnFile, :type => "radio", :value => "Yes"

            %label.radio-inline No
            = text_field :fb_agency, :TaxExemptOnFile, :type => "radio", :value => "No"
            %p
            / Temporary Solution For Appearance
        .row.yes-no-quest
          %p.pull-left.col-sm-6
            = label :fb_agency, :IRSVerification, 'Was it verified on the IRS Automatic Revocation of Exemption List?'
          .pull-right.col-sm-12
            %label.radio-inline Yes
            =text_field :fb_agency, :IRSVerification, :type => "radio", :value => "Yes"
            %label.radio-inline No
            = text_field :fb_agency, :IRSVerification, :type => "radio", :value => "No"
            %p
            / Temporary Solution For Appearance
        .row
          .col-xs-2.pull-left.col-sm-5
            =label :fb_agency, :DateOfVerification, "Date of Verification (Found at:"
            %a{:href => "http://www.irs.gov/charities/article/0,,name=240099.html"} http://www.irs.gov/charities/article/0,,name=240099.html
            = text_field :fb_agency, :DateOfVerification
        %br
        .row.yes-no-quest
          %p.pull-left.col-sm-6
            =label :fb_agency,:EEP, 'Emergency Food Program(EEP)?'
          .pull-right.col-sm-12
            %label.radio-inline Yes
            =text_field :fb_agency, :EEP, :type => "radio", :value => "Yes"
            %label.radio-inline No
            = text_field :fb_agency, :EEP, :type => "radio", :value => "No"
            %p
            / Temporary Solution For Appearance
        .row.pull-right.rm
          = submit_tag 'Next'

app/views/fb_agencies/page3.html.haml
%body
  !!! XML
  #wrapper
    = form_tag fb_agencies_url :method => :post do
      .form-group
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            =label :fb_agency, :DateOfContract, 'Date of Contract'
            =text_field :fb_agency, :DateOfContract
        %br
        .row.yes-no-quest
          %p.pull-left
            %b
              Meal Program
            %br
              %small (5 year certificate)
          .col-xs-2.pull-right.col-sm-10.rm
            %label.checkbox-inline  Soup Kitchen
            = text_field :fb_agency, :SoupKitchen,:type => "checkbox", :value => "Yes"
            %label.checkbox-inline Group Home
            = text_field :fb_agency, :GroupHome, :type => "checkbox", :value => "Yes"
            %label.checkbox-inline Shelter/Transitional Living
            = text_field :fb_agency, :Shelter, :type => "checkbox", :value => "Yes"
            %label.checkbox-inline Daycare
            = text_field :fb_agency, :Daycare, :type => "checkbox", :value => "Yes"
            %label.checkbox-inline  Youth Program/After School
            = text_field :fb_agency, :YouthProgram, :type => "checkbox", :value => "Yes"
            %p
        .row.yes-no-quest
          %p.pull-left
            %b
              Grocery Program
            %br
              %small (2 year certificate)
          .col-xs-2.pull-right.col-sm-10.rm
            %label.checkbox-inline Food Pantry
            = text_field :fb_agency, :FoodPantry, :type => "checkbox", :value => "Yes"
            %label.checkbox-inline Seasonal
            = text_field :fb_agency, :Seasonal, :type => "checkbox", :value => "Yes"
            %label.checkbox-inline Mobile Pantry
            = text_field :fb_agency, :MobilePantry, :type => "checkbox", :value => "Yes"
            %label.checkbox-inline Backpack
            = text_field :fb_agency, :Backpack, :type => "checkbox", :value => "Yes"
            %p
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :PersonInterviewed, 'Person Interviewed'
            = text_field :fb_agency, :PersonInterviewed
        .row
          .col-xs-2.pull-left.col-sm-4.lm
            = label :fb_agency, :DaysOfOperation, 'Days & times of operation'
            =text_field :fb_agency, :DaysOfOperation, :placeholder => "Ex. MWF, 9a - 12p", :type => "text"
        .row.yes-no-quest
          %p.pull-left.col-sm-6
            = label :fb_agency, :SingleAudit, 'Is your organization required to have a single audit?'
          .pull-right.col-sm-12
            %label.radio-inline Yes
            = text_field :fb_agency, :SingleAudit, :type => "radio", :value => "Yes"
            %label.radio-inline No
            = text_field :fb_agency, :SingleAudit, :type => "radio", :value => "No"
          %p.pull-left.col-sm-6
            %small (If YES, obtain a copy or ask the site to provide a copy of the most recent audit within the next 30 days)
        .row.yes-no-quest
          %p.pull-left.col-sm-6
            %b
              = label :fb_agency, :HandicapAccessible, 'Does the agency appear to be handicapped accessible?'
              .pull-right.col-sm-12
                %label.radio-inline Yes
                = text_field :fb_agency, :HandicapAccessible, :type => "radio", :value => "Yes"
                %label.radio-inline No
                = text_field :fb_agency, :HandicapAccessible, :type => "radio", :value => "No"
        .row.pull-right.rm
          = submit_tag 'Next'