config/routes.rb
Foodbank:: Application.routes.draw do 
    root 'sessions#new'
    #resources :forms, :fb_agencies, :validate_step_fb_agencies, :meal_programs, :grocery_plans, :food_safeties, :direct_connect_programs,
    #:ef_programs, :program_procedures, :signature_documents, :proxy_forms, :part_six_forms, :part_seven_eight_forms,
    resources :fb_agencies, :grocery_plans, :food_safeties, :meal_programs, :ef_programs, :direct_connect_programs, :part_six_forms, :part_seven_eight_forms, :forms

 

=begin
    resource :wizard do
        get :step1
        get :step2
        get :step3
    
        post :validate_step
    end
=end

   # get '/forms/step2'
   # get '/forms/step3'
    #get '/forms/fb_agencies/index'
    #get '/forms/foodsafety' 
    #get '/forms/mealplan'
    #get '/forms/groceryplan'
    #get '/forms/directconnect'
    #get '/forms/emergencyfood'
    #get '/forms/part6'
    #get '/forms/part7_8'
   # get '/forms.css'

   

    get '/forms/foodsafety'
    get '/forms/mealplan'
    get '/forms/groceryplan'
    get '/forms/directconnect'
    #get '/forms/emergencyfood'
    get '/forms/part6'
    get '/forms/part7_8'
    get "howto/:howto"=>"howto#show"
    
   get 'signup'  => 'users#new'
   resources :users
  
   get '/login' => 'sessions#new'
  
   post 'login' => 'sessions#create'
  
   delete 'logout' => 'sessions#destroy'

 
end

app/views/wizards/step1.html.haml
%body
  !!! XML
  #wrapper

      
    = form_tag  validate_step_wizard_url :method => :post do
      = hidden_field_tag "current_step", "step1"
      .form-group
        .row
          .col-xs-2.pull-right.col-sm-3.rm
            = label :fb_agency, :AgencyCounty, 'Agency County'
            = text_field :fb_agency, :AgencyCounty
            
        .row
          .col-xs-2.pull-right.col-sm-3.rm
            = label :fb_agency, :AgencyNumber, 'Agency #'
            = text_field :fb_agency, :AgencyNumber
            
        .row
          .text-center
            %h2 Network Partner Monitoring Form
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :TodaysDate, "Today's Date"
            = text_field :fb_agency, :TodaysDate
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :DofLastMonitor,  'Date of Last Monitor'
            = text_field :fb_agency, :DofLastMonitor
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :AgencyName, 'Agency Name'
            = text_field :fb_agency, :AgencyName
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :AgencyNumber, 'Agency #'
            = text_field :fb_agency, :AgencyNumber
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :ParentAgency, 'Parent Agency'
            = text_field :fb_agency, :ParentAgency
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :PAgencyNum, 'Agency #'
            = text_field :fb_agency, :PAgencyNum
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :SiteAddress, 'Site Address'
            = text_field :fb_agency, :SiteAddress
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :SiteNumber, 'Phone #'
            = text_field :fb_agency, :SiteNumber 
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :ContactName, 'Contact Name'
            = text_field :fb_agency, :ContactName
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :ContactNum,  'Phone #'
            = text_field :fb_agency, :ContactNum
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :Director, "Director's Name"
            = text_field :fb_agency, :Director
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :DirectorNum, 'Phone #'
            = text_field :fb_agency, :DirectorNum
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :AdditionalContact, 'Additional Contact Name'
            = text_field :fb_agency, :AdditionalContact
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :AdditionalNum,'Phone #'
            = text_field :fb_agency, :AdditionalNum
        .row.pull-right.rm
          = submit_tag 'Next'

app/views/wizards/step2.html.haml
%body
  !!! XML
  #wrapper

    
    = form_tag validate_step_wizard_url :method => :post do
      = hidden_field_tag "current_step", "step2"
      .form-group
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :PrimaryEmail, 'Primary Email'
            = text_field :fb_agency, :PrimaryEmail
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :DateMostRecentTraining, 'Date of Most Recent Food Safety Training'
            = text_field :fb_agency, :DateMostRecentTraining
        .row.yes-no-quest
          %p.pull-left.col-sm-6
            = label :fb_agency, :TaxExemptOnFile, 'Does Northern Illinois Food Bank have current verification of tax exempt status on file?'
          .pull-right.col-sm-12
            %label.radio-inline Yes
            = text_field :fb_agency, :TaxExemptOnFile, :type => "radio", :value => "Yes"

            %label.radio-inline No
            = text_field :fb_agency, :TaxExemptOnFile, :type => "radio", :value => "No"
            %p
            / Temporary Solution For Appearance
        .row.yes-no-quest
          %p.pull-left.col-sm-6
            = label :fb_agency, :IRSVerification, 'Was it verified on the IRS Automatic Revocation of Exemption List?'
          .pull-right.col-sm-12
            %label.radio-inline Yes
            =text_field :fb_agency, :IRSVerification, :type => "radio", :value => "Yes"
            %label.radio-inline No
            = text_field :fb_agency, :IRSVerification, :type => "radio", :value => "No"
            %p
            / Temporary Solution For Appearance
        .row
          .col-xs-2.pull-left.col-sm-5
            =label :fb_agency, :DateOfVerification, "Date of Verification (Found at:"
            %a{:href => "http://www.irs.gov/charities/article/0,,name=240099.html"} http://www.irs.gov/charities/article/0,,name=240099.html
            = text_field :fb_agency, :DateOfVerification
        %br
        .row.yes-no-quest
          %p.pull-left.col-sm-6
            =label :fb_agency,:EEP, 'Emergency Food Program(EEP)?'
          .pull-right.col-sm-12
            %label.radio-inline Yes
            =text_field :fb_agency, :EEP, :type => "radio", :value => "Yes"
            %label.radio-inline No
            = text_field :fb_agency, :EEP, :type => "radio", :value => "No"
            %p
            / Temporary Solution For Appearance
        .row.pull-right.rm
          = submit_tag 'Next'
          

            

app/views/wizards/step3.html.haml
%body
  !!! XML
  #wrapper
      
    = form_tag validate_step_wizard_url :method => :post do
      = hidden_field_tag "current_step", "step3"
      .form-group
      .row
        .col-xs-2.pull-left.col-sm-2.lm
          =label :fb_agency, :DateOfContract, 'Date of Contract'
          =text_field :fb_agency, :DateOfContract
        %br
        .row.yes-no-quest
          %p.pull-left
            %b
              Meal Program
            %br
              %small (5 year certificate)
          .col-xs-2.pull-right.col-sm-10.rm
            %label.checkbox-inline  Soup Kitchen
            = text_field :fb_agency, :SoupKitchen,:type => "checkbox", :value => "Yes"
            %label.checkbox-inline Group Home
            = text_field :fb_agency, :GroupHome, :type => "checkbox", :value => "Yes"
            %label.checkbox-inline Shelter/Transitional Living
            = text_field :fb_agency, :Shelter, :type => "checkbox", :value => "Yes"
            %label.checkbox-inline Daycare
            = text_field :fb_agency, :Daycare, :type => "checkbox", :value => "Yes"
            %label.checkbox-inline  Youth Program/After School
            = text_field :fb_agency, :YouthProgram, :type => "checkbox", :value => "Yes"
            %p
        .row.yes-no-quest
          %p.pull-left
            %b
              Grocery Program
            %br
              %small (2 year certificate)
          .col-xs-2.pull-right.col-sm-10.rm
            %label.checkbox-inline Food Pantry
            = text_field :fb_agency, :FoodPantry, :type => "checkbox", :value => "Yes"
            %label.checkbox-inline Seasonal
            = text_field :fb_agency, :Seasonal, :type => "checkbox", :value => "Yes"
            %label.checkbox-inline Mobile Pantry
            = text_field :fb_agency, :MobilePantry, :type => "checkbox", :value => "Yes"
            %label.checkbox-inline Backpack
            = text_field :fb_agency, :Backpack, :type => "checkbox", :value => "Yes"
            %p
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :PersonInterviewed, 'Person Interviewed'
            = text_field :fb_agency, :PersonInterviewed
        .row
          .col-xs-2.pull-left.col-sm-4.lm
            = label :fb_agency, :DaysOfOperation, 'Days & times of operation'
            =text_field :fb_agency, :DaysOfOperation, :placeholder => "Ex. MWF, 9a - 12p", :type => "text"
        .row.yes-no-quest
          %p.pull-left.col-sm-6
            = label :fb_agency, :SingleAudit, 'Is your organization required to have a single audit?'
          .pull-right.col-sm-12
            %label.radio-inline Yes
            = text_field :fb_agency, :SingleAudit, :type => "radio", :value => "Yes"
            %label.radio-inline No
            = text_field :fb_agency, :SingleAudit, :type => "radio", :value => "No"
          %p.pull-left.col-sm-6
            %small (If YES, obtain a copy or ask the site to provide a copy of the most recent audit within the next 30 days)
        .row.yes-no-quest
          %p.pull-left.col-sm-6
            %b
              = label :fb_agency, :HandicapAccessible, 'Does the agency appear to be handicapped accessible?'
              .pull-right.col-sm-12
                %label.radio-inline Yes
                = text_field :fb_agency, :HandicapAccessible, :type => "radio", :value => "Yes"
                %label.radio-inline No
                = text_field :fb_agency, :HandicapAccessible, :type => "radio", :value => "No"
        .row.pull-right.rm
          = submit_tag 'Next'