config/routes.rb
Foodbank:: Application.routes.draw do 
    root 'sessions#new'
    #resources :forms, :fb_agencies, :validate_step_fb_agencies, :meal_programs, :grocery_plans, :food_safeties, :direct_connect_programs,
    #:ef_programs, :program_procedures, :signature_documents, :proxy_forms, :part_six_forms, :part_seven_eight_forms,
    resources :fb_agencies, :grocery_plans, :food_safeties, :meal_programs, :ef_programs, :direct_connect_programs, :part_six_forms, :part_seven_eight_forms, :forms

 

=begin
    resource :wizard do
        get :step1
        get :step2
        get :step3
    
        post :validate_step
    end
=end

   # get '/forms/step2'
   # get '/forms/step3'
    #get '/forms/fb_agencies/index'
    #get '/forms/foodsafety' 
    #get '/forms/mealplan'
    #get '/forms/groceryplan'
    #get '/forms/directconnect'
    #get '/forms/emergencyfood'
    #get '/forms/part6'
    #get '/forms/part7_8'
   # get '/forms.css'

   

    get '/forms/foodsafety'
    get '/forms/mealplan'
    get '/forms/groceryplan'
    get '/forms/directconnect'
    #get '/forms/emergencyfood'
    get '/forms/part6'
    get '/forms/part7_8'
    get "howto/:howto"=>"howto#show"
    
   get 'signup'  => 'users#new'
   resources :users
  
   get '/login' => 'sessions#new'
  
   post 'login' => 'sessions#create'
  
   delete 'logout' => 'sessions#destroy'

 
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
    before_action :require_user, only: [:index, :show]
    def index
        @forms = Form.all
    end
    
    def new
        
    end
    
end

app/views/forms/directconnect.html.haml
%body
  !!! XML
  #wrapper
    = form_tag direct_connect_programs_url :method => :post do
      .form-group
        .row
          .col-xs-2.pull-right.col-sm-1.rm
            %label{:for => "agency_num"} Agency #
            %input#agency_num.form-control{:disabled => "disabled", :type => "text"}/
        .row
          .text-center
            %h3 Part IV: Direct Connect Program
        .row.yes-no-quest
          %p.pull-left.col-sm-6
            = label :direct_connect_program, :DirectConnectParticipate, 'Does the partner participate in DIRECT CONNECT?'
            %small (pick up at a retail store)
          .col-xs-2.pull-left.col-sm-2.lm
            %label.radio-inline Yes
            = text_field :direct_connect_program, :DirectConnectParticipate, :type => "radio", :value => "Yes"
            %label.radio-inline No
            = text_field :direct_connect_program, :DirectConnectParticipate, :type => "radio", :value => "No"
            %p
        .row
          .col-xs-2.pull-left.col-sm-6.lm
            = label :direct_connect_program, :ColdFoodTransport, 'If yes, how are cold foods kept cold during transport?'
          .col-xs-2.pull-left.col-sm-2.lm
            = text_field :direct_connect_program, :ColdFoodTransport
        .row.yes-no-quest
          %p.pull-left.col-sm-6
            %b
            = label :direct_connect_program, :PickupPaperwork,  'Do they have copies of their pick up paper work?'
            %small (must keep on file for 7 years)
          .col-xs-2.pull-left.col-sm-2.lm
            %label.radio-inline Yes
            = text_field :direct_connect_program, :PickupPaperworkPickupPaperwork, :type => "radio", :value => "Yes"
            %label.radio-inline No
            = text_field :direct_connect_program, :PickupPaperwork, :type => "radio", :value => "No"
            %p
        .row.yes-no-quest
          %p.pull-left.col-sm-6
            = label :direct_connect_program, :SampleTemps, 'Are sample temperatures documented at the time of pick up and delivery?'
          .col-xs-2.pull-left.col-sm-2.lm
            %label.radio-inline Yes
            = text_field :direct_connect_program, :SampleTemps, :type => "radio", :value => "Yes"
            %label.radio-inline No
            = text_field :direct_connect_program, :SampleTemps, :type => "radio", :value => "No"
            %p
        .row.yes-no-quest
          %p.pull-left.col-sm-6
            = label :direct_connect_program, :TempControlledDevices, 'Do they have temperature controlled devices to be used during food transportation?'
          .col-xs-2.pull-left.col-sm-2.lm
            %label.radio-inline Yes
            = text_field :direct_connect_program, :TempControlledDevices, :type => "radio", :value => "Yes"
            %label.radio-inline No
            = text_field :direct_connect_program, :TempControlledDevices, :type => "radio", :value => "No"
            %p
        .row.pull-right.rm
          = submit_tag 'Next'

app/views/forms/foodsafety.html.haml
%body
  !!! XML
  #wrapper
    = form_tag food_safeties_url :method => :post do
      .form-group
        .row
          .col-xs-2.pull-right.col-sm-1.rm
            %label{:for => "agency_num"} Agency #
            %input#agency_num.form-control{:disabled => "disabled", :type => "text"}/
        .row
          .text-center
            %h3 Part III: Food Safety, Storage and Inventory (ALL PROGRAMS)
          .row.yes-no-quest
            .col-xs-2.pull-left.col-sm-4.lm
              = label :food_safety, :RequireAPermit, 'Does the Local Health Department require a permit?'            
            .col-xs-2.pull-left.col-sm-3.lm
              %label.radio-inline Yes
              = text_field :food_safety, :RequireAPermit, :type =>"radio", :value => "Yes"
              %label.radio-inline Not Required
              = text_field :food_safety, :RequireAPermit, :type => "radio", :value => "Not Required"
              %p
          .row
            .col-xs-2.pull-left.col-sm-4.lm
              %p
                %small (If yes, provide copy of permit and date of last inspection)
          %br
          .row
            .col-xs-2.pull-left.col-sm-2.lm
              = label :food_safety, :PermitScore,  'Score'
              = text_field :food_safety, :PermitScore
            .col-xs-2.pull-left.col-sm-2.lm
              = label :food_safety, :PermitDate, 'Date'
              = text_field :food_safety, :PermitDate
          %br
          .row.yes-no-quest
            .col-xs-2.pull-left.col-sm-4.lm
              = label :food_safety, :CleaningSchedulePosted, 'Is there a regular cleaning schedule established and posted?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :food_safety, :CleaningSchedulePosted, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :food_safety, :CleaningSchedulePosted, :type => "radio", :value => "No"
              %p
          %br
          .row.yes-no-quest
            .col-xs-2.pull-left.col-sm-4.lm
              %b
              = label :food_safety, :PestControlRoutine,  'Does the site have routine professional pest control?'
              %small (Get Copy of Contract or Invoice)
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :food_safety, :PestControlRoutine, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :food_safety, :PestControlRoutine, :type => "radio", :value => "No"
              %p
          .row
            .col-xs-2.pull-left.col-sm-3.lm
              = label :food_safety, :PestControlCompany, 'With whom was the last inspection'
              = text_field :food_safety, :PestControlCompany
            .col-xs-2.pull-left.col-sm-2.lm
              = label :food_safety, :PestControlLastVisit, 'Last inspection date'
              = text_field :food_safety, :PestControlLastVisit
          %br
          .row
            .pull-left.col-sm-3
              = label :food_safety, :FoodStorageLocation, 'Is all food stored at this location?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :food_safety, :FoodStorageLocation, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :food_safety, :FoodStorageLocation, :type => "radio", :value => "No"
          .row.yes-no-quest
            %p.pull-left.col-sm-3
              = label :food_safety, :AdditionalStorage, 'If no, where is the additional storage'
            .col-xs-2.pull-left.col-sm-1.lm
              = text_field :food_safety, :AdditionalStorage
          %br
          .row.yes-no-quest
            %p.pull-left.col-sm-3
              = label :food_safety, :FoodSixInchesOffFloor, 'Is all food stored 6 inches off the floor?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :food_safety, :FoodSixInchesOffFloor, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :food_safety, :FoodSixInchesOffFloor, :type => "radio", :value => "No"
              %p
          .row.yes-no-quest
            %p.pull-left.col-sm-3
              = label :food_safety, :FridgeTempBetween35and40F, 'Are refrigerator tempsbetween 35°  and 40°  F?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :food_safety, :FridgeTempBetween35and40F, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :food_safety, :FridgeTempBetween35and40F, :type => "radio", :value => "No"
              %p
          .row.yes-no-quest
            %p.pull-left.col-sm-3
              = label :food_safety, :FreezerTemp0orBelow, 'Are freezers 0°  F or below?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :food_safety, :FreezerTemp0orBelow, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :food_safety, :FreezerTemp0orBelow, :type => "radio", :value => "No"
          .row.yes-no-quest
            %p.pull-left.col-sm-6
              = label :food_safety, :WorkingThermometers, 'Are there working thermometers in all storage areas and temps in proper range?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :food_safety, :WorkingThermometers, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :food_safety, :WorkingThermometers, :type => "radio", :value => "No"
              %p
          .row.yes-no-quest
            %p.pull-left.col-sm-4
              = label :food_safety, :TempLogsMaintainedAndPosted, 'Are temperature logs maintained and posted?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :food_safety, :TempLogsMaintainedAndPosted, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :food_safety, :TempLogsMaintainedAndPosted, :type => "radio", :value => "No"
              %p
          .row.pull-right.rm
            = submit_tag 'Next'

app/views/forms/groceryplan.html.haml
%body
  !!! XML
  #wrapper
    = form_tag grocery_plans_url :method => :post do
      .form-group
        .row
          .col-xs-2.pull-right.col-sm-1.rm
            %label{:for => "agency_num"} Agency #
            %input#agency_num.form-control{:disabled => "disabled", :type => "text"}/
          .row
            .text-center
              %h3 Part II: Grocery Program Information
          .row.yes-no-quest
            %p.pull-left.col-sm-6
              %b
                'What type of distribution method is utilized?'
              %br
            .col-xs-2.pull-right.col-sm-12.rm
              %label.checkbox-inline Choice Pantry
              = text_field :grocery_plan, :ChoicePantry, :type => "checkbox", :value => "Yes"
              %label.checkbox-inline Traditional
              = text_field :grocery_plan, :Traditional, :type => "checkbox", :value => "Yes"
              %label.checkbox-inline Combination
              = text_field :grocery_plan, :Combination, :type => "checkbox", :value => "Yes"
              %label.checkbox-inline Other
              =text_field :grocery_plan, :Other,:type => "checkbox", :value => "Yes"
          .row
            %p.pull-left.col-sm-12
              %small (If other please explain)
            %br
            .col-xs-2.pull-left.col-sm-6.lm
              = text_field :grocery_plan, :OtherDistributonUtilized
          .row
            .col-xs-2.pull-left.col-sm-6.lm
              = label :grocery_plan, :FequencyHouseholdCanRecieveFood, 'How often can a household receive food from the grocery program'
            .col-xs-2.pull-left.col-sm-3.lm  
              = text_field :grocery_plan, :FequencyHouseholdCanRecieveFood
          %br
          .row
            .col-xs-2.pull-left.col-sm-6.lm
              = label :grocery_plan, :AvgNumPeopleServered, 'Average number of people served per month'
            .col-xs-2.pull-left.col-sm-2.lm  
              = text_field :grocery_plan, :AvgNumPeopleServered
          %br
          .row
            .col-xs-2.pull-left.col-sm-6.lm
              = label :grocery_plan, :AvgNumHouseholdsServered, "Average number of households served per month"
            .col-xs-2.pull-left.col-sm-2.lm  
              = text_field :grocery_plan, :AvgNumHouseholdsServered
          %br
          .row
            .col-xs-2.pull-left.col-sm-6.lm
              = label :grocery_plan, :FoodPerHousehold, 'Estimated amount of food provided per household, in days or pounds'
            .col-xs-2.pull-left.col-sm-2.lm  
              = text_field :grocery_plan, :FoodPerHousehold
          %br
          .row.yes-no-quest
            %p.pull-left.col-sm-6
              = label :grocery_plan, :GeoServiceArea, 'Does the grocery program have a designated geographic service area?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              =text_field :grocery_plan, :GeoServiceArea, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :grocery_plan, :GeoServiceArea, :type => "radio", :value => "No"
              %p
          .row.yes-no-quest
            %p.pull-left.col-sm-6
              = label :grocery_plan, :FSClassAttended, 'Has a member of the grocery program attended food safety class?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :grocery_plan, :FSClassAttended, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :grocery_plan, :FSClassAttended, :type => "radio", :value => "No"
              %p
          .row
            .col-xs-2.pull-left.col-sm-2.lm
              = label :grocery_plan, :FSCDate, 'Date'
              = text_field :grocery_plan, :FSCDate
            .col-xs-2.pull-left.col-sm-2.lm
              = label :grocery_plan, :FSCAttendeeName, 'Name'
              = text_field :grocery_plan, :FSCAttendeeName
          %br
          .row.yes-no-quest
            %p.pull-left.col-sm-6
              = label :grocery_plan, :FeesRequired, 'Are fees/donations/memberships required of the clients for any service?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :grocery_plan, :FeesRequired, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :grocery_plan, :FeesRequired, :type => "radio", :value => "No"
              %p
          .row
            .col-xs-2.pull-left.col-sm-6.rm
              = label :grocery_plan, :FeesExplained, 'If yes, Please Explain'
              = text_area  :grocery_plan, :FeesExplained, :rows => "4", :style => "width:40em"
        .row.yes-no-quest
          .row
            .col-xs-2.pull-left.col-sm-6.lm
              = label :grocery_plan, :FundingSource, 'Funding Source'
              = text_field :grocery_plan, :FundingSource
          %br
          .row.yes-no-quest
            %p.pull-left.col-sm-6
              = label :grocery_plan, :DaysOfOperationVisible, 'Are days and hours of operation posted on the outside of the facility & visible to clients?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :grocery_plan, :DaysOfOperationVisible, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :grocery_plan, :DaysOfOperationVisible, :type => "radio", :value => "No"
              %p
          .row
            .col-xs-2.pull-left.col-sm-6.lm
              = label :grocery_plan, :FoodAssistanceRequirements, 'What are the requirements for food assistance'
              = text_area :grocery_plan, :FoodAssistanceRequirements, :rows => "4", :style => "width:40em"
        .row.yes-no-quest
          %br
          .row.yes-no-quest
            %p.pull-left.col-sm-6
              = label :grocery_plan, :TrackClientParticipation, 'Does the grocery program track client participation?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :grocery_plan, :TrackClientParticipation, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :grocery_plan, :TrackClientParticipation, :type => "radio", :value => "No"
              %p
          .row.yes-no-quest
            %p.pull-left.col-sm-6
              = label :grocery_plan, :Confidential, 'Is intake process done in a confidential manner?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :grocery_plan, :Confidential, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :grocery_plan, :Confidential, :type => "radio", :value => "No"
              %p
          .row.yes-no-quest
            %p.pull-left.col-sm-6
              = label :grocery_plan, :Delivery, 'Does grocery program deliver food to clients?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :grocery_plan, :Delivery, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :grocery_plan, :Delivery, :type => "radio", :value => "No"
              %p
          .row.pull-right.rm
            = submit_tag 'Next'

app/views/forms/index.html.haml
%body
  !!! XML
  #wrapper
    = form_tag fb_agencies_url :method => :post do
      = hidden_field_tag "current_step", "index"
      .form-group
        .row
          .col-xs-2.pull-right.col-sm-3.rm
            = label :fb_agency, :AgencyCounty, 'Agency County'
            = text_field :fb_agency, :AgencyCounty
            
        .row
          .col-xs-2.pull-right.col-sm-3.rm
            = label :fb_agency, :AgencyNumber, 'Agency #'
            = text_field :fb_agency, :AgencyNumber
            
        .row
          .text-center
            %h2 Network Partner Monitoring Form
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :TodaysDate, "Today's Date"
            = text_field :fb_agency, :TodaysDate
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :DofLastMonitor,  'Date of Last Monitor'
            = text_field :fb_agency, :DofLastMonitor
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :AgencyName, 'Agency Name'
            = text_field :fb_agency, :AgencyName
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :AgencyNumber, 'Agency #'
            = text_field :fb_agency, :AgencyNumber
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :ParentAgency, 'Parent Agency'
            = text_field :fb_agency, :ParentAgency
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :PAgencyNum, 'Agency #'
            = text_field :fb_agency, :PAgencyNum
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :SiteAddress, 'Site Address'
            = text_field :fb_agency, :SiteAddress
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :SiteNumber, 'Phone #'
            = text_field :fb_agency, :SiteNumber 
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :ContactName, 'Contact Name'
            = text_field :fb_agency, :ContactName
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :ContactNum,  'Phone #'
            = text_field :fb_agency, :ContactNum
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :Director, "Director's Name"
            = text_field :fb_agency, :Director
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :DirectorNum, 'Phone #'
            = text_field :fb_agency, :DirectorNum
        .row
          .col-xs-2.pull-left.col-sm-2.lm
            = label :fb_agency, :AdditionalContact, 'Additional Contact Name'
            = text_field :fb_agency, :AdditionalContact
          .col-xs-2.pull-left.col-sm-2.rm
            = label :fb_agency, :AdditionalNum,'Phone #'
            = text_field :fb_agency, :AdditionalNum
        .row.pull-right.rm
          = submit_tag 'Next'

app/views/forms/mealplan.html.haml
%body
  !!! XML
  #wrapper
    = form_tag meal_programs_url :method => :post do
      .form-group
        .row
          .text-center
            %h3 Part I: Meal Program Information
            %br
          .row.yes-no-quest
            %p.pull-left.col-sm-6
              = label :meal_program, :MonthlyServiceData, 'Monthly Service data reported?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :meal_program, :MonthlyServiceData, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :meal_program, :MonthlyServiceData, :type => "radio", :value => "No"
              %p
          .row
            .col-xs-2.pull-left.col-sm-5.lm
              = label :meal_program, :NumMealsServeredLastMonth, 'Number of meals served last month:'
              = text_field :meal_program, :NumMealsServeredLastMonth
          %br
          .row.yes-no-quest
            %p.pull-left.col-sm-6
              = label :meal_program, :SafeFoodHandlingCertification, 'Does Food Bank have the Safe Food Handling Certification on file?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :meal_program, :SafeFoodHandlingCertification, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :meal_program, :SafeFoodHandlingCertification, :type => "radio", :value => "No"
              %p
          .row
            .pull-right.col-sm-12
              = label :meal_program, :CertificationName, 'Name/Date'
              = text_field :meal_program, :CertificationName
          %br    
          .row.yes-no-quest
            %p.pull-left.col-sm-6
              = label :meal_program, :FeesDonations, 'Are fees/donations/memberships required of the clients for any service?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :meal_program, :FeesDonations, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :meal_program, :FeesDonations, :type => "radio", :value => "No"
              %p
          .row
            .col-xs-2.pull-left.col-sm-6.rm
              = label :meal_program, :FeesExplained, 'If yes, please explain'
              = text_area :meal_program, :FeesExplained, :rows => "4", :style => "width:40em"
          %br
          .row
            .col-xs-2.pull-left.col-sm-6.lm
              =label :meal_program, :FundingSource, 'Funding Source'
              = text_field :meal_program, :FundingSource
          %br
          .row.yes-no-quest
            %p.pull-left.col-sm-6
              = label :meal_program, :SFHCertificationPosted, 'Is Safe Food Handling Certification posted in kitchen?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :meal_program, :SFHCertificationPosted, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :meal_program, :SFHCertificationPosted, :type => "radio", :value => "No"
              %p
          .row.yes-no-quest
            %p.pull-left.col-sm-6
              = label :meal_program, :OperationHoursPosted, 'Are days and hours of operation posted on the outside of the facility & visible to clients?'
            .col-xs-2.pull-left.col-sm-2.lm
              %label.radio-inline Yes
              = text_field :meal_program, :OperationHoursPosted, :type => "radio", :value => "Yes"
              %label.radio-inline No
              = text_field :meal_program, :OperationHoursPosted, :type => "radio", :value => "No"
              %p
          .row
            .col-xs-2.pull-left.col-sm-6.lm
              = label :meal_program, :FoodAssistanceRequirements, 'What are the requirements for food assistance'
              = text_field :meal_program, :FoodAssistanceRequirements
          %br    
          .row
            .col-xs-2.pull-left.col-sm-2.lm
              = label :meal_program, :FoodAssistanceRequirements, 'Average number of people served per month:'
              = text_field :meal_program, :FoodAssistanceRequirements
          %br
          .row
            %p.col-xs-2.pull-left.col-sm-6.lm
              %b Group Homes / Transitional Living
          %br
          .row
            .col-xs-2.pull-left.col-sm-2.rm
              = label :meal_program, :GroupHomeCount, 'Number Of Residents', :size =>"2"
              = text_field :meal_program, :GroupHomeCount
            .col-xs-2.pull-left.col-sm-2.lm
              = label :meal_program, :GroupHomeNumMeals, 'Number of meals served daily:'
              = text_field :meal_program, :GroupHomeNumMeals
            .col-xs-2.pull-left.col-sm-2.lm
              = label :meal_program, :MealPrepParticipation, 'Who participates in meal preparation?'
              = text_field :meal_program, :MealPrepParticipation
          %br
          .row
            %p.col-xs-2.pull-left.col-sm-6.lm
              %b School / Daycare Program
          %br
          .row
            .col-xs-2.pull-left.col-sm-2.lm
              = label :meal_program, :SchoolFee,  'Number of free lunches:'
              = text_field :meal_program, :SchoolFee
            .col-xs-2.pull-left.col-sm-3.lm
              = label :meal_program, :NumSchoolReducedLunches,  'Number of reduced lunches:'
              = text_field :meal_program, :NumSchoolReducedLunches
            .col-xs-2.pull-left.col-sm-2.lm
              = label :meal_program, :SchoolFee, 'Lunch fee $'
              = text_field :meal_program, :SchoolFee
            .col-xs-2.pull-left.col-sm-2.lm
              = label :meal_program, :SchoolReducedFee, 'Reduced lunch fee $'
              = text_field :meal_program, :SchoolReducedFee
          .row.pull-right.rm
            = submit_tag 'Next'